apiVersion: v2
name: nginx-vault-helm
description: A Helm chart for deploying an Nginx web server with customizable replicas, content and an optional Hashicorp Vault sidecar container.
version: 1.0.0
appVersion: 1.21.1

# Define input variables with validation checks
values:
  replicaCount:
    default: 1
    description: "Number of Nginx replicas in the pod (must be between 1 and 10)"
    type: int
    validators:
      min: 1
      max: 10
  webpageContent:
    default: "Hello World"
    description: "Content of the Nginx web page"
    type: string
  vaultEnabled:
    default: false
    description: "Enable Hashicorp Vault sidecar container (true/false)"
    type: bool

# Define deployment, service and sidecar container configurations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: WEBPAGE_CONTENT
              value: {{ .Values.webpageContent }}
          {{- if .Values.vaultEnabled }}
          - name: vault
            image: hashicorp/vault:latest
            env:
              - name: VAULT_ADDR
                value: http://localhost:8200
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
